---
name: App-EditorTools
version: 0.04
author:
  - 'Mark Grimes, E<lt>mgrimes@cpan.orgE<gt>'
abstract: Command line tools to leverage PPIx::EditorTools (and maybe more)
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-EditorTools
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/app-editortools/tree/master
requires:
  App::Cmd: 0
  FindBin::libs: 0
  PPIx::EditorTools: 0
  perl: 5.008
build_requires:
  IPC::Run3: 0
  Test::Differences: 0
provides:
  App::EditorTools:
    file: lib/App/EditorTools.pm
    version: 0.04
  App::EditorTools::Command::IntroduceTemporaryVariable:
    file: lib/App/EditorTools/Command/IntroduceTemporaryVariable.pm
  App::EditorTools::Command::RenamePackage:
    file: lib/App/EditorTools/Command/RenamePackage.pm
  App::EditorTools::Command::RenamePackageFromPath:
    file: lib/App/EditorTools/Command/RenamePackageFromPath.pm
  App::EditorTools::Command::RenameVariable:
    file: lib/App/EditorTools/Command/RenameVariable.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
